import { Hotel, Destination, MoodCategory } from "./types";

export const hotels: Hotel[] = [
  {
    id: "hotel-1",
    name: "The Azure Cove Resort",
    brand: "Luxury Collection",
    tier: "Luxury",
    location: "Maldives",
    city: "Malé Atoll",
    country: "Maldives",
    description: "An overwater paradise with crystal-clear lagoons, private villas perched above turquoise waters, and world-class diving. Each villa features glass floors revealing vibrant coral reefs below.",
    image: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&q=80",
      "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&q=80",
      "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80",
    ],
    rating: 4.9,
    reviewCount: 1247,
    pricePerNight: 850,
    currency: "USD",
    amenities: ["Private Pool", "Spa", "Diving Center", "Fine Dining", "Butler Service", "Water Sports"],
    tags: ["tropical", "beach", "luxury", "romantic", "overwater", "diving", "serene"],
    coordinates: { lat: 4.1755, lng: 73.5093 },
    bonvoyPointsPerNight: 85000,
    roomTypes: [
      { id: "rt-1a", name: "Overwater Villa", description: "Stunning overwater villa with glass floor panels and private deck", pricePerNight: 850, maxGuests: 2, bedType: "King", size: "95 sqm", image: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=600&q=80", amenities: ["Glass Floor", "Private Deck", "Outdoor Shower", "Minibar"] },
      { id: "rt-1b", name: "Beach Villa with Pool", description: "Beachfront villa with private infinity pool and garden", pricePerNight: 1200, maxGuests: 3, bedType: "King", size: "150 sqm", image: "https://images.unsplash.com/photo-1602002418082-a4443e081dd1?w=600&q=80", amenities: ["Private Pool", "Garden", "Beach Access", "Outdoor Dining"] },
      { id: "rt-1c", name: "Sunset Water Suite", description: "Premium overwater suite facing the sunset with personal butler", pricePerNight: 2100, maxGuests: 2, bedType: "King", size: "200 sqm", image: "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=600&q=80", amenities: ["Butler Service", "Wine Cellar", "Jacuzzi", "Telescope"] },
    ],
  },
  {
    id: "hotel-2",
    name: "Alpine Summit Lodge",
    brand: "Autograph Collection",
    tier: "Premium",
    location: "Swiss Alps",
    city: "Zermatt",
    country: "Switzerland",
    description: "A cozy mountain retreat nestled at the foot of the Matterhorn, offering ski-in/ski-out access, rustic-chic interiors with roaring fireplaces, and panoramic alpine views.",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80",
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80",
      "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 892,
    pricePerNight: 450,
    currency: "USD",
    amenities: ["Ski-in/Ski-out", "Spa", "Fireplace Lounge", "Mountain Restaurant", "Heated Pool", "Ski Storage"],
    tags: ["mountain", "winter", "cozy", "skiing", "rustic", "scenic", "adventure"],
    coordinates: { lat: 46.0207, lng: 7.7491 },
    bonvoyPointsPerNight: 45000,
    roomTypes: [
      { id: "rt-2a", name: "Alpine Deluxe Room", description: "Warm wood-paneled room with Matterhorn view", pricePerNight: 450, maxGuests: 2, bedType: "Queen", size: "40 sqm", image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600&q=80", amenities: ["Mountain View", "Fireplace", "Minibar", "Balcony"] },
      { id: "rt-2b", name: "Summit Suite", description: "Spacious suite with separate living area and panoramic windows", pricePerNight: 750, maxGuests: 4, bedType: "King", size: "85 sqm", image: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=600&q=80", amenities: ["Panoramic View", "Fireplace", "Kitchenette", "Private Sauna"] },
    ],
  },
  {
    id: "hotel-3",
    name: "Sakura Garden Hotel",
    brand: "W Hotels",
    tier: "Premium",
    location: "Tokyo, Japan",
    city: "Tokyo",
    country: "Japan",
    description: "A sleek, ultra-modern hotel in the heart of Shibuya, blending Japanese zen aesthetics with cutting-edge design. Features a rooftop infinity pool overlooking the Tokyo skyline.",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
      "https://images.unsplash.com/photo-1590490360182-c33d955a75fa?w=800&q=80",
    ],
    rating: 4.7,
    reviewCount: 2134,
    pricePerNight: 380,
    currency: "USD",
    amenities: ["Rooftop Pool", "Spa", "Fitness Center", "3 Restaurants", "Bar", "Concierge"],
    tags: ["urban", "modern", "culture", "nightlife", "zen", "skyline", "foodie"],
    coordinates: { lat: 35.6762, lng: 139.6503 },
    bonvoyPointsPerNight: 38000,
    roomTypes: [
      { id: "rt-3a", name: "Zen Studio", description: "Minimalist room with tatami area and city view", pricePerNight: 380, maxGuests: 2, bedType: "King", size: "35 sqm", image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80", amenities: ["City View", "Rain Shower", "Smart Controls", "Tea Set"] },
      { id: "rt-3b", name: "Tokyo Sky Suite", description: "Corner suite with wrap-around windows and soaking tub", pricePerNight: 680, maxGuests: 2, bedType: "King", size: "70 sqm", image: "https://images.unsplash.com/photo-1590490360182-c33d955a75fa?w=600&q=80", amenities: ["Skyline View", "Soaking Tub", "Living Room", "Sake Bar"] },
    ],
  },
  {
    id: "hotel-4",
    name: "Coastal Breeze Resort & Spa",
    brand: "Ritz-Carlton",
    tier: "Luxury",
    location: "Amalfi Coast, Italy",
    city: "Positano",
    country: "Italy",
    description: "Perched on dramatic cliffs overlooking the Mediterranean, this resort offers terraced gardens, a cliffside infinity pool, and authentic Italian culinary experiences with ingredients from the on-site garden.",
    image: "https://images.unsplash.com/photo-1455587734955-081b22074882?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1455587734955-081b22074882?w=800&q=80",
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80",
    ],
    rating: 4.9,
    reviewCount: 1560,
    pricePerNight: 720,
    currency: "USD",
    amenities: ["Infinity Pool", "Spa", "Cooking Classes", "Wine Cellar", "Private Beach", "Boat Tours"],
    tags: ["coastal", "romantic", "luxury", "mediterranean", "foodie", "scenic", "cultural"],
    coordinates: { lat: 40.6281, lng: 14.4849 },
    bonvoyPointsPerNight: 72000,
    roomTypes: [
      { id: "rt-4a", name: "Sea View Room", description: "Elegant room with terrace overlooking the Mediterranean", pricePerNight: 720, maxGuests: 2, bedType: "King", size: "45 sqm", image: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80", amenities: ["Sea View", "Terrace", "Marble Bath", "Minibar"] },
      { id: "rt-4b", name: "Cliffside Suite", description: "Two-story suite carved into the cliff with private plunge pool", pricePerNight: 1350, maxGuests: 3, bedType: "King", size: "120 sqm", image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&q=80", amenities: ["Plunge Pool", "Two Stories", "Dining Area", "Butler"] },
    ],
  },
  {
    id: "hotel-5",
    name: "Savanna Starlight Camp",
    brand: "Edition",
    tier: "Luxury",
    location: "Serengeti, Tanzania",
    city: "Serengeti",
    country: "Tanzania",
    description: "A luxury tented camp in the heart of the Serengeti offering front-row seats to the Great Migration. Sleep under canvas with all the comforts of a five-star hotel, surrounded by the African wilderness.",
    image: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=800&q=80",
      "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80",
      "https://images.unsplash.com/photo-1504432842672-1a79f78e4084?w=800&q=80",
    ],
    rating: 4.9,
    reviewCount: 456,
    pricePerNight: 950,
    currency: "USD",
    amenities: ["Game Drives", "Bush Dining", "Star Gazing", "Spa", "Private Guide", "Photography Tours"],
    tags: ["safari", "adventure", "wildlife", "nature", "luxury", "unique", "stargazing"],
    coordinates: { lat: -2.3333, lng: 34.8333 },
    bonvoyPointsPerNight: 95000,
    roomTypes: [
      { id: "rt-5a", name: "Safari Tent", description: "Luxury canvas tent with hardwood floors and bush views", pricePerNight: 950, maxGuests: 2, bedType: "King", size: "65 sqm", image: "https://images.unsplash.com/photo-1504432842672-1a79f78e4084?w=600&q=80", amenities: ["Bush View", "En-suite Bath", "Veranda", "Writing Desk"] },
      { id: "rt-5b", name: "Starlight Suite Tent", description: "Premium tent with retractable roof for stargazing from bed", pricePerNight: 1600, maxGuests: 2, bedType: "King", size: "100 sqm", image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=600&q=80", amenities: ["Stargazing Roof", "Private Deck", "Outdoor Bath", "Telescope"] },
    ],
  },
  {
    id: "hotel-6",
    name: "Manhattan Skyline Hotel",
    brand: "JW Marriott",
    tier: "Premium",
    location: "New York City, USA",
    city: "New York",
    country: "United States",
    description: "A sophisticated urban sanctuary in Midtown Manhattan with floor-to-ceiling windows, an acclaimed rooftop restaurant, and a world-class spa. Steps from Central Park, Times Square, and Broadway.",
    image: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&q=80",
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80",
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80",
    ],
    rating: 4.6,
    reviewCount: 3421,
    pricePerNight: 420,
    currency: "USD",
    amenities: ["Rooftop Bar", "Spa", "Fitness Center", "Restaurant", "Concierge", "Business Center"],
    tags: ["urban", "skyline", "business", "nightlife", "culture", "shopping", "theater"],
    coordinates: { lat: 40.7580, lng: -73.9855 },
    bonvoyPointsPerNight: 42000,
    roomTypes: [
      { id: "rt-6a", name: "City View Room", description: "Modern room with Manhattan skyline views", pricePerNight: 420, maxGuests: 2, bedType: "King", size: "38 sqm", image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80", amenities: ["City View", "Marble Bath", "Work Desk", "Minibar"] },
      { id: "rt-6b", name: "Park View Suite", description: "Expansive suite with Central Park views and butler pantry", pricePerNight: 890, maxGuests: 3, bedType: "King", size: "80 sqm", image: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=600&q=80", amenities: ["Park View", "Living Room", "Butler Pantry", "Soaking Tub"] },
    ],
  },
  {
    id: "hotel-7",
    name: "Coral Reef Retreat",
    brand: "Westin",
    tier: "Premium",
    location: "Great Barrier Reef, Australia",
    city: "Cairns",
    country: "Australia",
    description: "An eco-luxury resort on a private island within the Great Barrier Reef Marine Park. Features sustainable architecture, world-class snorkeling right off the beach, and a marine biology center.",
    image: "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80",
      "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80",
      "https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=800&q=80",
    ],
    rating: 4.7,
    reviewCount: 678,
    pricePerNight: 520,
    currency: "USD",
    amenities: ["Snorkeling", "Diving", "Marine Center", "Eco-Spa", "Restaurant", "Kayaking"],
    tags: ["tropical", "beach", "eco", "diving", "nature", "island", "adventure"],
    coordinates: { lat: -16.9186, lng: 145.7781 },
    bonvoyPointsPerNight: 52000,
    roomTypes: [
      { id: "rt-7a", name: "Reef View Bungalow", description: "Eco-designed bungalow with reef views and outdoor shower", pricePerNight: 520, maxGuests: 2, bedType: "King", size: "55 sqm", image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=600&q=80", amenities: ["Reef View", "Outdoor Shower", "Hammock", "Minibar"] },
      { id: "rt-7b", name: "Island Villa", description: "Secluded villa with private beach access and plunge pool", pricePerNight: 880, maxGuests: 4, bedType: "King", size: "110 sqm", image: "https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=600&q=80", amenities: ["Private Beach", "Plunge Pool", "Kitchen", "Snorkel Gear"] },
    ],
  },
  {
    id: "hotel-8",
    name: "Desert Mirage Oasis",
    brand: "St. Regis",
    tier: "Luxury",
    location: "Marrakech, Morocco",
    city: "Marrakech",
    country: "Morocco",
    description: "A palatial riad-style hotel in the heart of Marrakech, featuring ornate mosaic courtyards, a rooftop terrace overlooking the Atlas Mountains, and an authentic hammam spa experience.",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 1089,
    pricePerNight: 390,
    currency: "USD",
    amenities: ["Hammam Spa", "Rooftop Terrace", "Courtyard Pool", "Moroccan Restaurant", "Cooking Classes", "Guided Tours"],
    tags: ["desert", "cultural", "exotic", "historic", "foodie", "romantic", "artistic"],
    coordinates: { lat: 31.6295, lng: -7.9811 },
    bonvoyPointsPerNight: 39000,
    roomTypes: [
      { id: "rt-8a", name: "Riad Room", description: "Traditional room with mosaic details and courtyard view", pricePerNight: 390, maxGuests: 2, bedType: "King", size: "42 sqm", image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600&q=80", amenities: ["Courtyard View", "Mosaic Bath", "Sitting Area", "Tea Service"] },
      { id: "rt-8b", name: "Royal Suite", description: "Palatial suite with private terrace and mountain views", pricePerNight: 780, maxGuests: 3, bedType: "King", size: "95 sqm", image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&q=80", amenities: ["Mountain View", "Private Terrace", "Living Room", "Personal Butler"] },
    ],
  },
  {
    id: "hotel-9",
    name: "Northern Lights Lodge",
    brand: "Tribute Portfolio",
    tier: "Premium",
    location: "Tromsø, Norway",
    city: "Tromsø",
    country: "Norway",
    description: "A striking glass-roofed lodge above the Arctic Circle, designed for optimal aurora borealis viewing. Features heated glass igloos, husky sledding, and a Nordic spa with ice plunge pools.",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80",
      "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&q=80",
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 534,
    pricePerNight: 580,
    currency: "USD",
    amenities: ["Aurora Viewing", "Nordic Spa", "Husky Sledding", "Restaurant", "Ice Bar", "Snowshoeing"],
    tags: ["arctic", "aurora", "winter", "unique", "adventure", "nature", "romantic"],
    coordinates: { lat: 69.6492, lng: 18.9553 },
    bonvoyPointsPerNight: 58000,
    roomTypes: [
      { id: "rt-9a", name: "Glass Igloo", description: "Heated glass igloo with unobstructed sky views", pricePerNight: 580, maxGuests: 2, bedType: "King", size: "30 sqm", image: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=600&q=80", amenities: ["Glass Ceiling", "Heated Floor", "Aurora Alert", "Minibar"] },
      { id: "rt-9b", name: "Arctic Cabin Suite", description: "Luxury log cabin with hot tub and panoramic aurora windows", pricePerNight: 920, maxGuests: 4, bedType: "King", size: "80 sqm", image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600&q=80", amenities: ["Private Hot Tub", "Panoramic Windows", "Fireplace", "Kitchen"] },
    ],
  },
  {
    id: "hotel-10",
    name: "Bamboo Forest Ryokan",
    brand: "Luxury Collection",
    tier: "Luxury",
    location: "Kyoto, Japan",
    city: "Kyoto",
    country: "Japan",
    description: "A serene ryokan-style hotel hidden within an ancient bamboo grove, offering traditional kaiseki cuisine, private onsen baths, and tea ceremony experiences in a setting of extraordinary natural beauty.",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
      "https://images.unsplash.com/photo-1590490360182-c33d955a75fa?w=800&q=80",
    ],
    rating: 4.9,
    reviewCount: 876,
    pricePerNight: 620,
    currency: "USD",
    amenities: ["Private Onsen", "Kaiseki Dining", "Tea Ceremony", "Zen Garden", "Meditation", "Bamboo Walk"],
    tags: ["zen", "cultural", "nature", "serene", "traditional", "wellness", "romantic"],
    coordinates: { lat: 35.0116, lng: 135.7681 },
    bonvoyPointsPerNight: 62000,
    roomTypes: [
      { id: "rt-10a", name: "Tatami Suite", description: "Traditional tatami room with garden view and private onsen", pricePerNight: 620, maxGuests: 2, bedType: "Futon (King)", size: "50 sqm", image: "https://images.unsplash.com/photo-1590490360182-c33d955a75fa?w=600&q=80", amenities: ["Garden View", "Private Onsen", "Tatami", "Tea Set"] },
      { id: "rt-10b", name: "Imperial Bamboo Villa", description: "Standalone villa within the bamboo grove with wraparound engawa", pricePerNight: 1100, maxGuests: 3, bedType: "King", size: "120 sqm", image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80", amenities: ["Private Garden", "Two Onsens", "Dining Room", "Butler"] },
    ],
  },
  {
    id: "hotel-11",
    name: "Harbor Lights Hotel",
    brand: "Marriott",
    tier: "Select",
    location: "Sydney, Australia",
    city: "Sydney",
    country: "Australia",
    description: "A vibrant waterfront hotel overlooking Sydney Harbour, with direct views of the Opera House and Harbour Bridge. Perfect base for exploring the city's beaches, culture, and culinary scene.",
    image: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&q=80",
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80",
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80",
    ],
    rating: 4.5,
    reviewCount: 2890,
    pricePerNight: 280,
    currency: "USD",
    amenities: ["Harbor View", "Pool", "Fitness Center", "Restaurant", "Bar", "Tour Desk"],
    tags: ["urban", "coastal", "culture", "nightlife", "beach", "foodie", "iconic"],
    coordinates: { lat: -33.8568, lng: 151.2153 },
    bonvoyPointsPerNight: 28000,
    roomTypes: [
      { id: "rt-11a", name: "Harbor View Room", description: "Bright room with Opera House and harbor views", pricePerNight: 280, maxGuests: 2, bedType: "King", size: "32 sqm", image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80", amenities: ["Harbor View", "Work Desk", "Rain Shower", "Minibar"] },
      { id: "rt-11b", name: "Bridge Suite", description: "Corner suite with dual views of Opera House and Harbour Bridge", pricePerNight: 520, maxGuests: 3, bedType: "King", size: "65 sqm", image: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=600&q=80", amenities: ["Dual Views", "Living Area", "Soaking Tub", "Bar Area"] },
    ],
  },
  {
    id: "hotel-12",
    name: "Vineyard Estate Hotel",
    brand: "Autograph Collection",
    tier: "Premium",
    location: "Tuscany, Italy",
    city: "Siena",
    country: "Italy",
    description: "A restored 15th-century estate surrounded by rolling vineyards and olive groves. Features an acclaimed winery, farm-to-table restaurant, and outdoor infinity pool overlooking the Tuscan countryside.",
    image: "https://images.unsplash.com/photo-1455587734955-081b22074882?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1455587734955-081b22074882?w=800&q=80",
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 743,
    pricePerNight: 350,
    currency: "USD",
    amenities: ["Winery", "Wine Tasting", "Pool", "Farm Restaurant", "Cooking Classes", "Cycling"],
    tags: ["countryside", "wine", "foodie", "romantic", "historic", "relaxing", "cultural"],
    coordinates: { lat: 43.3188, lng: 11.3308 },
    bonvoyPointsPerNight: 35000,
    roomTypes: [
      { id: "rt-12a", name: "Vineyard Room", description: "Charming room in the historic wing with vineyard views", pricePerNight: 350, maxGuests: 2, bedType: "Queen", size: "35 sqm", image: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80", amenities: ["Vineyard View", "Antique Furniture", "En-suite Bath", "Welcome Wine"] },
      { id: "rt-12b", name: "Estate Suite", description: "Grand suite with original frescoes, terrace, and private garden", pricePerNight: 650, maxGuests: 3, bedType: "King", size: "90 sqm", image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&q=80", amenities: ["Frescoed Ceilings", "Private Garden", "Wine Fridge", "Terrace"] },
    ],
  },
];

export const destinations: Destination[] = [
  { id: "dest-1", name: "Maldives", country: "Maldives", description: "Paradise islands with overwater villas and crystal lagoons", image: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&q=80", tags: ["tropical", "beach", "luxury", "romantic"], climate: "Tropical", bestMonths: ["Nov", "Apr"], activities: ["Diving", "Snorkeling", "Spa", "Sunset Cruise"] },
  { id: "dest-2", name: "Swiss Alps", country: "Switzerland", description: "Majestic peaks, world-class skiing, and charming alpine villages", image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80", tags: ["mountain", "winter", "skiing", "adventure"], climate: "Alpine", bestMonths: ["Dec", "Mar"], activities: ["Skiing", "Hiking", "Fondue", "Train Tours"] },
  { id: "dest-3", name: "Tokyo", country: "Japan", description: "A dazzling blend of ultra-modern tech and ancient tradition", image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80", tags: ["urban", "culture", "foodie", "modern"], climate: "Temperate", bestMonths: ["Mar", "May", "Oct", "Nov"], activities: ["Temple Visits", "Street Food", "Shopping", "Sumo"] },
  { id: "dest-4", name: "Amalfi Coast", country: "Italy", description: "Dramatic cliffs, pastel villages, and the sparkling Mediterranean", image: "https://images.unsplash.com/photo-1455587734955-081b22074882?w=800&q=80", tags: ["coastal", "romantic", "foodie", "scenic"], climate: "Mediterranean", bestMonths: ["May", "Sep"], activities: ["Boat Tours", "Limoncello Tasting", "Hiking", "Beach"] },
  { id: "dest-5", name: "Serengeti", country: "Tanzania", description: "Endless plains teeming with wildlife and unforgettable sunsets", image: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=800&q=80", tags: ["safari", "adventure", "wildlife", "nature"], climate: "Tropical Savanna", bestMonths: ["Jun", "Oct"], activities: ["Game Drives", "Hot Air Balloon", "Bush Dining", "Star Gazing"] },
  { id: "dest-6", name: "New York City", country: "United States", description: "The city that never sleeps — endless energy, culture, and cuisine", image: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&q=80", tags: ["urban", "culture", "nightlife", "shopping"], climate: "Temperate", bestMonths: ["Apr", "Jun", "Sep", "Dec"], activities: ["Broadway", "Central Park", "Museums", "Dining"] },
  { id: "dest-7", name: "Tromsø", country: "Norway", description: "Gateway to the Arctic and the magical Northern Lights", image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80", tags: ["arctic", "aurora", "winter", "unique"], climate: "Subarctic", bestMonths: ["Sep", "Mar"], activities: ["Aurora Viewing", "Dog Sledding", "Whale Watching", "Ice Fishing"] },
  { id: "dest-8", name: "Marrakech", country: "Morocco", description: "A sensory feast of colors, spices, and architectural wonders", image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80", tags: ["desert", "cultural", "exotic", "historic"], climate: "Semi-arid", bestMonths: ["Mar", "May", "Oct", "Nov"], activities: ["Souk Shopping", "Hammam", "Desert Tours", "Cooking Classes"] },
];

export const moodCategories: MoodCategory[] = [
  { id: "mood-1", name: "Romance", emoji: "\u2764\uFE0F", description: "Candlelit dinners, sunset strolls, and intimate getaways", image: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&q=80", tags: ["romantic", "luxury", "serene", "beach"], gradient: "from-rose-500 to-pink-600" },
  { id: "mood-2", name: "Adventure", emoji: "\u26F0\uFE0F", description: "Thrilling experiences from mountain peaks to ocean depths", image: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=800&q=80", tags: ["adventure", "hiking", "diving", "safari", "skiing"], gradient: "from-orange-500 to-amber-600" },
  { id: "mood-3", name: "Wellness", emoji: "\uD83E\uDDD8", description: "Rejuvenate your mind, body, and soul at world-class spas", image: "https://images.unsplash.com/photo-1540555700478-4be289fbec6e?w=800&q=80", tags: ["wellness", "spa", "zen", "nature", "serene"], gradient: "from-teal-500 to-emerald-600" },
  { id: "mood-4", name: "Culture", emoji: "\uD83C\uDFDB\uFE0F", description: "Immerse yourself in history, art, and local traditions", image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80", tags: ["cultural", "historic", "artistic", "traditional", "foodie"], gradient: "from-purple-500 to-violet-600" },
  { id: "mood-5", name: "Urban", emoji: "\uD83C\uDF03", description: "Vibrant cityscapes, world-class dining, and buzzing nightlife", image: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&q=80", tags: ["urban", "nightlife", "shopping", "foodie", "skyline"], gradient: "from-blue-500 to-indigo-600" },
  { id: "mood-6", name: "Nature", emoji: "\uD83C\uDF3F", description: "Escape to pristine landscapes and breathtaking natural wonders", image: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=800&q=80", tags: ["nature", "eco", "wildlife", "scenic", "island"], gradient: "from-green-500 to-lime-600" },
];

export function searchHotels(query: string): Hotel[] {
  const lowerQuery = query.toLowerCase();
  return hotels.filter(
    (hotel) =>
      hotel.name.toLowerCase().includes(lowerQuery) ||
      hotel.location.toLowerCase().includes(lowerQuery) ||
      hotel.city.toLowerCase().includes(lowerQuery) ||
      hotel.country.toLowerCase().includes(lowerQuery) ||
      hotel.tags.some((tag) => tag.includes(lowerQuery)) ||
      hotel.amenities.some((a) => a.toLowerCase().includes(lowerQuery))
  );
}

export function getHotelsByTags(tags: string[]): Hotel[] {
  return hotels
    .map((hotel) => ({
      hotel,
      score: tags.reduce(
        (acc, tag) =>
          acc + (hotel.tags.some((ht) => ht.includes(tag.toLowerCase())) ? 1 : 0),
        0
      ),
    }))
    .filter(({ score }) => score > 0)
    .sort((a, b) => b.score - a.score)
    .map(({ hotel }) => hotel);
}

export function getHotelById(id: string): Hotel | undefined {
  return hotels.find((h) => h.id === id);
}
